### ISSUE TITLE
Cannot find module 'interfaces/request.interface' or its corresponding type declarations.

### ISSUE THREAD

**Issue by thorizer** [getjerry/nest-casl#165]
this error is inside casl.module.d.ts
import { AuthorizableRequest } from 'interfaces/request.interface'
![Code_xr1k8drzPo](https://user-images.githubusercontent.com/13587810/142883975-5e76bb40-8d15-45c5-9064-bd4780e4a076.png)
![Code_abu2ApGllQ](https://user-images.githubusercontent.com/13587810/142883990-1e66bbd7-a63a-40cd-b6de-b977284861b3.png)
;

**Comment by liquidautumn** [comment]
Fixed in #166, closing
