### ISSUE TITLE
Question: How to create tests using nest-casl

### ISSUE THREAD

**Issue by RobertCharron** [getjerry/nest-casl#167]
I was able to implement nest-casl relatively easily which was very nice, and made it very easy to use. 

However when it comes to creating test cases similar to the CASL guide ( https://casl.js.org/v4/en/advanced/debugging-testing ) , I have had no luck. Are there any working examples provided on how to test?

**Comment by liquidautumn** [comment]
I'm testing the lib with e2e tests on client Nest app, you can use similar approach in your application. Check https://github.com/getjerry/nest-casl/tree/master/src/__specs__ for implementation details.

**Comment by RobertCharron** [comment]
@liquidautumn Thank you! I missed that there was examples there. I will take this approach.

**Comment by liquidautumn** [comment]
@RobertCharron should have mentioned it in readme, will do now.
