### ISSUE TITLE
Typeorm entities instead of dto and how to get rid of resolvers?

### ISSUE THREAD

**Issue by sviluppo** [getjerry/nest-casl#183]
Hello, 

i am pretty new to nestjs and i am trying to implement a RBAC with predefined roles and permissions into a project.
e.g. https://casl.js.org/v5/en/cookbook/roles-with-static-permissions
I checked mostly of the nestjs-casl repo and also accesscontrol/acl ones and i think that this one is the simplest to set up also because is structured on splitted permissions file that helps a lot to have a clean code.

I am not using GraphQL and i don't know it very well, i have understood that resolvers are in the repo because it relies on it.
Th readme was a little confusing on the part because there are resolvers but no controller, that could be found in the files.

Also i saw that you are using dto to get the schema object that is passed to casl permissions.

It's possible use this without resolvers and passing Typeorm entity class instead of dto?
I tried to play a little bit to use them changing subject type detection on `ability.factory.ts` 
https://casl.js.org/v5/en/guide/subject-type-detection

Would make sense? or the structure of this module cannot be easily changed?

**Comment by liquidautumn** [comment]
This lib was designed GraphQL first, but it can be used with controllers and I know people already using it this way. Check [testing app controller](https://github.com/getjerry/nest-casl/blob/master/src/__specs__/app/post/post.controller.ts) for the reference.

Regarding using Typeorm entities instead of DTOs, while you probably could make it working, I'd advice against it. Typeorm entities describe shape of database tables while DTOs describe shape of the API, having them separate, despite some repetition, makes things cleaner and helps keep application/api layer decoupled from infrastructure details.

**Comment by sviluppo** [comment]
Thank you so much for the answer.

Ok, i understand your point and kinda agree with the logic.
The only thing that bother me a little with DTOs is that the logic is very clear if you think it as form/data stream but if you think about them as API/model shape in that case would be better a class or an interface? maybe?
Repetition kills me a bit, but i will follow your tip.

**Comment by liquidautumn** [comment]
Not sure I got the question, in Nest DTOs are classes to allow injection and decoration, ie with validators.

**Comment by sviluppo** [comment]
Yes but i didn't find an example where a class of dto is used to define a model except for GraphQL [section](https://docs.nestjs.com/graphql/resolvers#object-types), if you check this [example](https://docs.nestjs.com/controllers) they are not defining `CatDto` but things like `createCatDto` where field inside are related to controller actions.

So my logic was that if i am not using GraphQL would make more sense not use Dto TypeObject Schema but instead define my models with a class/interface and use controller.

GraphQL  => Dto TypeObject Model => Resolvers
No GraphQL  => Class/interface Model => Controllers 

I don't know if now is more clear.  XD
