### ISSUE TITLE
`@UseAbility` does not allow string based subject

### ISSUE THREAD

**Issue by andreialecu** [getjerry/nest-casl#197]
You can define permissions like:

```ts
export const userPermissions: Permissions<Roles, Subjects, Actions> = {
  everyone({ user, can }) {
    can(Actions.read, 'User', { userId: user.id });
  },
};
```

However, the types of the `@UseAbility` decorator cannot take a string for the subject parameter so `@UseAbility(Actions.read, 'User')` shows a type error. 

It can be `//@ts-ignore`d and everything works. It would be great to fix the type however.

**Comment by ruscon** [comment]
this. is
```
type Subjects = InferSubjects<'User' | typeof User>;
```

**Comment by andreialecu** [comment]
Oh I see. Cool.

**Comment by andreialecu** [comment]
Actually this was about `@UseAbility`. In the permissions it already worked.

**Comment by ruscon** [comment]
You can create custom fake class `User` or `CaslUser` and use it
