### ISSUE TITLE
V 1.6.13 has introduced breaking changes

### ISSUE THREAD

**Issue by HMilbradt** [getjerry/nest-casl#516]
https://github.com/getjerry/nest-casl/releases/tag/v1.6.13

This PR has removed the `get` method from ConditionsProxy.  Is this project supposed to be following SEMVER?  If so, this should have been published as a V2 release, or left the deprecated behavior in.

**Comment by liquidautumn** [comment]
Restored get() method in #530
Thus versions between v1.6.13 and v1.6.17 inclusive are not following semver, v1.6.18 will have it fixed.
